FROM python:3.9.16

# Set the working directory to /app
WORKDIR /app

RUN pip install mlflow
# Copy the current directory contents into the container at /app
COPY . /app

# Expose port 5000 for the MLflow server
EXPOSE 5000

# Start the MLflow server
CMD ["mlflow", "server", "--host", "0.0.0.0", "--port", "5000"]
