FROM python:3.9-slim

COPY requirements.txt /app/requirements.txt
WORKDIR /app
RUN pip install --no-cache-dir -r requirements.txt

COPY . /app

ENV MLFLOW_TRACKING_URI=http://mlflow-server:5000

CMD ["python", "script.py"]
